# -*- coding: utf-8 -*-
"""CropRecommendation_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nm89Fyohp12GSA1TJp56GbxX2mUd8wJy
"""


import joblib
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


import pandas as pd
import io

df = pd.read_csv('mlModel\Crop_Recommendation.csv')
#print(df)

"""df.info()

df.columns"""

X = df.loc[:, df.columns != 'Crop']
Y = df['Crop']

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

# Initialize the model
clf = DecisionTreeClassifier()

# Train the model
clf.fit(X_train, y_train)
y_pred_train = clf.predict(X_train)
y_pred = clf.predict(X_test)


accuracy_score(y_train,y_pred_train)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")





joblib.dump(clf, 'backend\model.pkl')
joblib.dump(list(df['Crop'].astype('category').cat.categories), 'backend\classes.pkl')

